apiVersion: apps/v1
kind: Deployment
metadata:
  name: sirato-db-deployment
spec:
  selector:
    matchLabels:
      run: sirato-db
  replicas: 1
  template:
    metadata:
      labels:
        run: sirato-db
    spec:
      containers:
      - name: sirato-db
        image: mongo:5.0.8
        ports:
        - containerPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: sirato-db
  labels:
    run: sirato-db
spec:
  ports:
  - port: 27017
    protocol: TCP
  selector:
    run: sirato-db
